Fix C99 errors because of some recent refactoring work.
Modules/_librabbitmq/connection.c: In function ‘PyList_ToAMQArray’:
Modules/_librabbitmq/connection.c:303:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
Modules/_librabbitmq/connection.c:303:5: note: use option -std=c99 or -std=gnu99 to compile your code

Modules/_librabbitmq/connection.c: In function ‘AMQTable_toPyDict’:
Modules/_librabbitmq/connection.c:484:9: error: ‘for’ loop initial declarations are only allowed in C99 mode

Modules/_librabbitmq/connection.c: In function ‘AMQArray_toPyList’:
Modules/_librabbitmq/connection.c:556:9: error: ‘for’ loop initial declarations are only allowed in C99 mode

Modules/_librabbitmq/connection.c: In function ‘PyRabbitMQ_recv’:
Modules/_librabbitmq/connection.c:1245:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
Modules/_librabbitmq/connection.c:1280:13: error: ‘for’ loop initial declarations are only allowed in C99 mode